### PR TITLE
Rename refers field to subject

### PR DESCRIPTION
**Pull request by sajayantony**
Fixes correspond to the the image spec changes
- https://github.com/opencontainers/image-spec/pull/950

Signed-off-by: Sajay Antony <sajaya@microsoft.com>

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]

**Review by dmcgowan — APPROVED** [review]

**Comment by sudo-bmitch** [comment]
CI should be fixed if this is rebased.

**Review by vbatts — APPROVED** [review]
:pray:

**Comment by sajayantony** [comment]
Rebased and CI is now passing. 
Please help review this again @vbatts @sudo-bmitch @dmcgowan @jdolitsky.

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Review by jdolitsky — APPROVED** [review]

**Comment by mikebrow** [comment]
reads much better, I think.. Thx @sajayantony

**Pull request merged**
