### PR TITLE
Remove detail.md

### PR DESCRIPTION
**Pull request by sargun**
Although detail.md contained some useful information, the majority
of the document contained information that wasn't relevant to a
generic OCI registry.

It contained extraneous information, like information about authentication
that many registries may not use. In addition, the defined behaviours
were not conformant to the specification.

Signed-off-by: Sargun Dhillon <sargun@sargun.me>

### CODE REVIEW

**Comment by vbatts** [comment]
This was created during #178 and is referenced from the spec.md as:

>  Historical document describing original API endpoints and requests in detail

which could be why it is _wrong_, but also is not immediately obvious that it is obsolete historical context

**Comment by sargun** [comment]
I mean, isn't that what git history is for? Obsolete docs?

**Comment by vbatts** [comment]
yes. So, in addition to this PR, I would update [this line of the `spec.md`](https://github.com/opencontainers/distribution-spec/blame/main/spec.md#L564) to point to the v1.0 perma-url for that detail.md https://github.com/opencontainers/distribution-spec/blob/v1.0.0/detail.md or similar

**Comment by sargun** [comment]
@vbatts Done.

**Comment by vbatts** [comment]
cc @pmengelbert to H/T acknowledge his work :-)

**Review by vbatts — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
