### PR TITLE
fix: honor debug in reggie client

### LINKED ISSUE #521: Debug mode cannot be turned off for conformance test
`export OCI_DEBUG=0` is not working for the conformance test.

Root cause:
https://github.com/opencontainers/distribution-spec/blob/f453e4a5b541e3167d05ca371692984243533b17/conformance/setup.go#L188

https://github.com/opencontainers/distribution-spec/blob/f453e4a5b541e3167d05ca371692984243533b17/conformance/setup.go#L198-L207

Line 201 of `setup.go` always set the debug mode to `true` without evaluating the `debug` value from `OCI_DEBUG` at line 188.

### PR DESCRIPTION
**Pull request by shizhMSFT**
Fix #521

### CODE REVIEW

**Review by sudo-bmitch — CHANGES_REQUESTED** [review]
With this, the conformance report doesn't include any content when expanding the items.

**Comment by shizhMSFT** [comment]
@sudo-bmitch There is an option named `OCI_DEBUG`.

The conformance report does include contents when expanding the items when `OCI_DEBUG=0`. However, it also includes the `Authorization` header, which contains the credentials. And those credentials are leaked / exposed in the GitHub Action workflow since they are public.

For those public reports, we should set `OCI_DEBUG=1`.

**Comment by sudo-bmitch** [comment]
> The conformance report does include contents when expanding the items when `OCI_DEBUG=0`. However, it also includes the `Authorization` header, which contains the credentials.

There's a lot of other content that gets written to stdout/stderr when `OCI_DEBUG=1`, separate from the report. And there's a lot of useful details in the debug data written to the report that I believe we want to preserve. I think we'd either need a separate variable, or my preference, to censor the Authorization and similar headers from logs.

**Comment by jdolitsky** [comment]
There is code there intended to mask any secret values in debug: https://github.com/opencontainers/distribution-spec/blob/main/conformance/reporter.go#L450

Maybe its not catching some values?

**Comment by shizhMSFT** [comment]
@sudo-bmitch @jdolitsky Take this report as an example: https://github.com/shizhMSFT/oci-conformance-workflows/actions/runs/8251093925

I've set `OCI_DEBUG=0` but it still prints the authorization header (note: the credentials have been revoked after running the action).
Screenshot:
image

**Comment by shizhMSFT** [comment]
If I set `OCI_DEBUG=1`, I gets the same output as `OCI_DEBUG=0`. For instance: https://github.com/shizhMSFT/oci-conformance-workflows/actions/runs/8246450995

**Comment by sudo-bmitch** [comment]
Looks like our redaction was broken, possibly from an upstream change. See #529 for my recommended fix.

**Comment by shizhMSFT** [comment]
Closing this PR as it is fixed by #529

**Pull request closed without merging**
