### PR TITLE
Clean up README

### PR DESCRIPTION
**Pull request by atlaskerr**
Our README sucks. I was able to clean it up a bit thanks to the new `org` repo.

Let's use this PR for discussion on what everyone thinks should be included on the landing page.

### CODE REVIEW

**Comment by atlaskerr** [comment]
Yeah, it's pretty bare right now. It's gotta look bad before it looks good.

I'll work on this PR everytime I feel the need to procrastinate more important PRs :P

**Comment by jzelinskie** [comment]
I think the readme actually was more readable before.

I'd like to plug @kevinburke's talk on improving readability for documents like this. Honestly the whole spec should follow these guidelines: https://www.youtube.com/watch?v=sQP_hUNCrcE

**Comment by atlaskerr** [comment]
I'll watch the vid this weekend and give it another shot.

**Comment by vbatts** [comment]
On 01/02/19 10:20 -0800, Jimmy Zelinskie wrote:
>I'd like to plug @kevinburke's talk on improving readability for documents like this. Honestly the whole spec should follow these guidelines: https://www.youtube.com/watch?v=sQP_hUNCrcE

oooh. /me cues the vid

**Comment by vbatts** [comment]
Take another stab at this one :joy_cat:

**Pull request closed without merging**
