### PR TITLE
Add Slack info for discussions

### PR DESCRIPTION
**Pull request by SteveLasker**
Added slack info, including how to gain access to OCI Slack
Signed-off-by:  Steve Lasker <stevenlasker@hotmail.com>

### CODE REVIEW

**Comment by vbatts** [comment]
missing the DCO sign off

**Comment by vbatts** [comment]
also, this kind of thing should actually be consolidated into https://github.com/opencontainers/org/ now, as it's not exclusive to this repo

**Comment by SteveLasker** [comment]
Doing the PR on /org now

**Comment by vbatts** [comment]
LGTM

**Comment by jzelinskie** [comment]
LGTM

**Comment by jzelinskie** [comment]
@SteveLasker to pass CI you need to run `git commit --amend -s`.

**Comment by mikebrow** [comment]
Let's close this since https://github.com/opencontainers/org/pull/16 merged.

**Pull request closed without merging**
