### PR TITLE
Add josh maintainer

### PR DESCRIPTION
**Pull request by dmcgowan**
Josh has demonstrated a deep understanding of the specification and dedication to help with conformance and compatible for registries. Having another active and knowledgeable maintainer will help us drive the spec forward.

+ Updated Vincent's and Derek's email address as well to keep the file up to date.

### CODE REVIEW

**Comment by caniszczyk** [comment]
non binding +1 :)

**Comment by caniszczyk** [comment]
cc: @opencontainers/distribution-spec-maintainers

**Comment by jzelinskie** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
