### PR TITLE
1.0.0-rc2

### PR DESCRIPTION
**Pull request by jdolitsky**
this is for f576ba2ceac1f37396d2b378117bc5cc95740c42 to be tagged as 1.0.0-rc2
Email vote forthcoming

14 PRs merged since v1.0.0-rc1:

(#249) Use unique blobs for each workflow category
(#246) Modify conformance tests for single-shot uploads
(#245) Replace references to 'master' with 'main'
(#239) Describe single-request monolithic upload behavior
(#233) Rewrite README based on image spec
(#223) Fixing broken content negotiation link in spec.md
(#221) Adding faq again to replace #189
(#220) update category requirement language
(#218) Add placeholder for content negotiation
(#217) Push image to GHCR on release or master update
(#209) spec: add missing TOOMANYREQUESTS (429) error-code
(#208) Add test and spec section for HEAD requests
(#206) Resolve several open issues
(#204) Add cross-repository mounting section to spec/test

### CODE REVIEW

**Review by dmcgowan — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Probably not urgent, as it doesn't affect the spec itself, but looking through the repo, I see we now have both the `test` suite (contributed by Kinvolk) and the `conformance` suite in this repository; IIUC, the conformance suite was to replace the `test` suite; per @vbatts comment on https://github.com/opencontainers/distribution-spec/pull/39#issuecomment-566156150

> I want these changes to go in, for posterity sake. Even though the current consensus sounds like pulling in the conformance tests from the now-open-sourced projectquay is going to be our approach.

Wondering if the old one is still used, and if not, if this would be a good opportunity to clean up

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by jdolitsky** [comment]
@thaJeztah opened this issue and added to v1.0.0-rc3 milestone
https://github.com/opencontainers/distribution-spec/issues/254

**Comment by thaJeztah** [comment]
I doubt anyone is using it, but I saw that for previous releases, the version; in `specs-go/version.go` was updated  (and tagged), after which is was moved back to `-dev` https://github.com/opencontainers/distribution-spec/blob/v1.0.0-rc1/specs-go/version.go#L20-L28 https://github.com/opencontainers/distribution-spec/blob/9f55a32cdb9033c181ef61468ea4b4bc996c61dc/specs-go/version.go#L20-L28

**Comment by jdolitsky** [comment]
@thaJeztah - did not do it as part of this PR, but did do that again: https://github.com/opencontainers/distribution-spec/commit/54a28c9b3a390951ad981c5fe54a956b0c695483

**Comment by thaJeztah** [comment]
🙈 🙈 🙈  😞  oh!!! so sorry, I must've looked at this PR indeed, instead of at the tag and got confused

**Pull request merged**
