### PR TITLE
add Mike to maintainers

### PR DESCRIPTION
**Pull request by mikebrow**
add Mike :) 

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by jzelinskie** [comment]
These lists are usually alphabetical to avoid making people feel important (or unimportant).
You should run sort on the list.

**Comment by jzelinskie** [comment]
These lists are usually alphabetical to avoid making people feel important (or unimportant).
You should run sort on the list.

**Comment by mikebrow** [comment]
yeah but.. alpha by which field.. github, first name, last name, email.. other projects have a bit more formal format.. still others just add to the end.

**Comment by dmcgowan** [comment]
Looks like first name is used, that is definitely better ;)

**Comment by vbatts** [comment]
ALL THAT MATTERS IS THAT I'M NOT LAST ON THE LAST

**Comment by vbatts** [comment]
dang. I'm last again.

LGTM

**Comment by mikebrow** [comment]
oops to late Vince.. maybe we could use a different collating sequence.

**Comment by dmcgowan** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
