### PR TITLE
clarify where OCI-Chunk-Min-Length response headers are expected

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
LGTM, thanks for fixing that.

**Comment by rogpeppe** [comment]
From a practical point of view, I suspect the GET response to find the current offset should also return the chunk length, to better support stateless client resumption of uploads, but I've no idea if that's actually a current convention or not.

**Comment by sudo-bmitch** [comment]
The idea of setting this on the `POST` was that it's the first request, before any `PATCH` requests that would exceed the size. A client doing a chunked upload should use this for all subsequent requests of that blob.

**Comment by mvdan** [comment]
Should I do anything else to get this tiny clarification merged? Hopefully eight reviews aren't actually necessary :)

**Comment by sudo-bmitch** [comment]
> Should I do anything else to get this tiny clarification merged? Hopefully eight reviews aren't actually necessary :)

It just needs a second maintainer to approve. Copying the commit message into the PR may get more attention.

**Review by jdolitsky — APPROVED** [review]

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]

**Pull request merged**
