### PR TITLE
add jzelinskie to maintainers

### PR DESCRIPTION
**Pull request by jzelinskie**

### CODE REVIEW

**Comment by caniszczyk** [comment]
@jzelinskie git commit --amend -s, sign off the commit so the DCO passes

Then the @opencontainers/distribution-spec-maintainers can +1 this to add you

**Comment by jzelinskie** [comment]
woops totally forgot! should be good to go now

**Comment by vbatts** [comment]
aww yes, Jimmi Z

LGTM

(that rhymes :nerd_face: )

**Comment by dmcgowan** [comment]
LGTM

**Comment by vbatts** [comment]
interesting that pullapprove doesn't match you, derek...

**Comment by vbatts** [comment]
also, give the low maintainer numbers (3 at this moment https://github.com/opencontainers/distribution-spec/blob/b6c6b4f403f25e8ea81604c186fbc427a02c2c25/MAINTAINERS) the bylaws require a 2/3 ratio consensus, which is achieved with @dmcgowan and my LGTM

**Comment by vbatts** [comment]
lol, thanks @caniszczyk !

**Comment by stevvooe** [comment]
Welcome, @jzelinskie!

**Pull request merged**
