### PR TITLE
Add 307 as valid response for pulling blobs

### LINKED ISSUE #397: Pulling a blob doesn't specify 307 as a valid request
The specification currently expects a registry to return 200 status code on `GET`  on pulling a blob which may not be the case with many implementations. A 307 is a valid response and it seems like this might have been missed in the spec.

```
A GET request to an existing blob URL MUST provide the expected blob, with a response code that MUST be `200 OK`.
A successful response SHOULD contain the digest of the uploaded blob in the header `Docker-Content-Digest`.
If present, the value of this header MUST be a digest matching that of the response body.
```

### PR DESCRIPTION
**Pull request by sajayantony**
Fixes #397

### CODE REVIEW

**Comment by jdolitsky** [comment]
does this affect conformance tests at all, or are redirects simply followed? (i think they are)

**Comment by sudo-bmitch** [comment]
Redirects are followed automatically in Go (https://pkg.go.dev/net/http#Client). Does this need to be more generic than just on a blob GET, i.e. a statement at the top indicating http redirect status codes should be supported by clients according to https://www.rfc-editor.org/rfc/rfc7231#section-6.4

**Comment by jdolitsky** [comment]
> Does this need to be more generic than just on a blob GET

That would seem to cover all bases here

**Comment by mikebrow** [comment]
hmm.. adding redirects to the spec probably requires further consideration.

Was there any progress on creating a WG for auth?

**Comment by tianon** [comment]
> Was there any progress on creating a WG for auth?

https://github.com/opencontainers/tob/pull/119

**Comment by sajayantony** [comment]
Closing this PR for now but will consider bringing up the issue during the call. Currently multiple clients already follow redirects but seems like this is intermingled with auth.

**Pull request closed without merging**
