### PR TITLE
tag 1.1.0-rc4 (pt 2)

### PR DESCRIPTION
**Pull request by jdolitsky**
mailing list: https://groups.google.com/a/opencontainers.org/g/dev/c/aZqq6PjVGC4

## tag

This would mean tagging https://github.com/opencontainers/distribution-spec/commit/d7bc0ef0c72c3f91afbb161d1cbb0b14406cee65 as v1.1.0-rc4

## changes

- https://github.com/opencontainers/distribution-spec/pull/447
- https://github.com/opencontainers/distribution-spec/pull/450
- https://github.com/opencontainers/distribution-spec/pull/449
- https://github.com/opencontainers/distribution-spec/pull/451
- https://github.com/opencontainers/distribution-spec/pull/436
- https://github.com/opencontainers/distribution-spec/pull/444
- https://github.com/opencontainers/distribution-spec/pull/445
- https://github.com/opencontainers/distribution-spec/pull/452
- https://github.com/opencontainers/distribution-spec/pull/453
- https://github.com/opencontainers/distribution-spec/pull/465
- https://github.com/opencontainers/distribution-spec/pull/478
- https://github.com/opencontainers/distribution-spec/pull/473
- https://github.com/opencontainers/distribution-spec/pull/482
- https://github.com/opencontainers/distribution-spec/pull/469
- https://github.com/opencontainers/distribution-spec/pull/488
- https://github.com/opencontainers/distribution-spec/pull/479
- https://github.com/opencontainers/distribution-spec/pull/489
- https://github.com/opencontainers/distribution-spec/pull/492
- https://github.com/opencontainers/distribution-spec/pull/493
- https://github.com/opencontainers/distribution-spec/pull/481
- https://github.com/opencontainers/distribution-spec/pull/500
- https://github.com/opencontainers/distribution-spec/pull/499
- https://github.com/opencontainers/distribution-spec/pull/491

## diff

https://github.com/opencontainers/distribution-spec/compare/v1.1.0-rc3...jdolitsky:distribution-spec:d7bc0ef

## votes

 - [x] @sudo-bmitch
 - [x] @dmcgowan
 - [x] @jzelinskie
 - [ ] @jonjohnsonjr
 - [x] @jdolitsky
 - [x] @mikebrow
 - [x] @stevvooe
 - [ ] @vbatts

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Review by jzelinskie — APPROVED** [review]

**Comment by stevvooe** [comment]
LGTM

**Review by stevvooe — APPROVED** [review]

**Review by mikebrow — APPROVED** [review]
LGTM with reservation, a final RC for 1.1 should resolve:
1) subject descriptor in this distribution spec should be made consistent with the image spec restrictions see https://github.com/opencontainers/image-spec/blob/main/descriptor.md dag requirements e.g. validation
2) a plan or fix is made for 1.1.0 or 1.1.x resolving the apparent breakage with 1.0 dag support https://github.com/opencontainers/distribution-spec/issues/459 
3) define what must accept means (in clear terms) with respect to receiving push of artifacts referring to an image that does not exist.. e.g. garbage collection appears to be only allowed here by the client.. where in prior 1.0 registry image implementations repo content management included ability of the registry to remove (gc) content that was no longer in a dag.

**Review by dmcgowan — APPROVED** [review]

**Review by vbatts — APPROVED** [review]
LGTM 🐐

**Pull request merged**
