### PR TITLE
1.0.0-rc3

### PR DESCRIPTION
**Pull request by jdolitsky**
this is for d77f1f5ef8c6d1711f4adef8ad5c564ec4551499 to be tagged as 1.0.0-rc3
Email vote forthcoming

4 PRs merged since v1.0.0-rc2:

(#263) Fix the generation of release PDF
(#261) Fix trivial typo in TOC of spec.md
(#259) Remove old test code
(#257) Fix link to Content Digests

### CODE REVIEW

**Review by dmcgowan — APPROVED** [review]

**Review by vbatts — APPROVED** [review]
LGTM

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by jzelinskie** [comment]
LGTM

**Comment by mikebrow** [comment]
@stevvooe voted LGTM via email making this unanimous

**Review by stevvooe — APPROVED** [review]
LGTM

**Comment by caniszczyk** [comment]
@jdolitsky you this also be tagged as v1.0, I can prepare a blog post announcing the final release :)

**Pull request merged**
