### PR TITLE
Add Brandon as maintainer

### PR DESCRIPTION
**Pull request by jdolitsky**
His dedication to OCI is without parallel

### CODE REVIEW

**Comment by imjasonh** [comment]
Hear hear!

**Comment by sudo-bmitch** [comment]
Aww thank you! I'll be happy to accept this is approved by the maintainers.

**Comment by sajayantony** [comment]
+1

**Comment by caniszczyk** [comment]
ping @dmcgowan @jonjohnsonjr

**Review by jonjohnsonjr — APPROVED** [review]

**Comment by jonjohnsonjr** [comment]
LGTM

**Review by dmcgowan — APPROVED** [review]

**Review by mikebrow — APPROVED** [review]
LGTM

**Pull request merged**
