### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by sudo-bmitch**
## Mailing list

This thread tracks the release votes: https://groups.google.com/a/opencontainers.org/g/dev/c/IAU_8SUjzBY

## Tag

This would mean tagging 0f98d91a0afe7ed3ab0f29349beed2bb4ba1507d as v1.1.0

## Changes

- 6eac9eb version: switch back to -dev (#274)
- f0d9826 Define the representation for a tag. (#256)
- e20e7f0 maint: bump conformance image tag for action
- 918840b Update spec.md use length (#256)
- edbe27f Remove detail.md (#280)
- a5fa19d Allow for automatic content discovery for cross-mounting blobs (#275)
- 87f4a24 Explain how clients can adopt automatic content discovery (#275)
- 728e5d0 Explain why automatic content discovery is optional (#275)
- eab7c61 Add go.mod (#283)
- 3a53900 .tool: add a go.mod (#285)
- 82ce0ac fix my email (#286)
- bb5ddab add CODEOWNERS (#286)
- 3f766f4 remove pullapprove (#286)
- ad9cc95 Move from Travis to GitHub Actions (#284)
- 028a295 Add newline to bottom of .gitignore (#284)
- 5520b6b use Go 1.15 as minimum version (#284)
- b6c971b content-negotiation: bring over the table from Sebastiaan (#226)
- 0946716 Add Jon Johnson as maintainer (#288)
- 78b5e4a Fix order and links in spec TOC (#294)
- 8831c78 Fix RFC link (#295)
- 7be5e85 Add test for automatic cross mounting behaviour (#297)
- 9173aad Add conformance test verifying that cross-repo mount fails "open" (#296)
- 30ff26d conformance: update dependencies etc (#300)
- 008aff6 Update Makefile CI images to latest versions (#304)
- 158fd47 version: bump main back to -dev
- ec90a2a Merge pull request from GHSA-mc8v-mgrf-8f4m
- 570d026 Merge pull request from GHSA-mc8v-mgrf-8f4m
- 3c7314c Bump github.com/opencontainers/image-spec in /conformance (#308)
- 5de2081 Add handling of unknown fields to conformance tests (#311)
- f3a6a75 spec: clarify handling regarding Content-type header (#309)
- ef947ba version: release v1.0.1 (#309)
- 5d83a35 version: bump main back to -dev (#309)
- a9a16ca Use one line per sentence (#310)
- 3c2316e Clarifications around manifest reference validation (#310)
- b501a83 extension proposal (#111)
- 0e4c0e6 ext: pull in Sajay and Stephen's iteration on extensions (#111)
- 6fd88c3 Updated the extensions spec with the new discover routes (#111)
- 97e3aef Added a section for reserved namespaces (#111)
- 83a789c Update ext/README.md (#111)
- 12ffe00 extensions: pulling in latest feedback (#111)
- 7590719 Build conformance images with semver tags (#313)
- 54a193f Document manifest size limit recommendation (#293)
- 2fbf2f9 spec.md: add note on legacy error codes (#326)
- 12e3bc3 Add Brandon as maintainer (#322)
- 204d4b4 clarify push manifest spec (#333)
- 0b25d69 Fix pagination link for extensions (#336)
- 51d16e0 Incorporate PR feedback (#336)
- d05ceb8 Add conformance test coverage for data field (#318)
- 41590d5 Working Group Proposal for Reference Types (#335)
- aa890a1 Working group updates (#339)
- 0712c1c Fix: #343 CI for gitvalidation (#345)
- 19e5fa5 Registries MUST accept refers to unknown manifests (#341)
- 2f998be Rename refers field to subject (#344)
- ada7b35 Fix referrers API query string example (#342)
- 8087d5c Updates GHA to versions and bumps Go to 1.17 (#346)
- bd87eee docs: Update release process docs with checklist (#350)
- 1dfa4f4 version: bump for 1.1.0-rc1 release (#348)
- 95bed23 version: switch back to -dev (#348)
- 315c7e0 conformance.test01Pull: Check client errors before using response object (#356)
- af2e081 Fix broken link to image indices in spec. (#371)
- 4e77264 Add Go 1.20 support (#381)
- 16cc054 Specify subject-processed response header (#379)
- 5025143 OCI-Subject: `<subject digest>` (#379)
- d06de52 Specify filters-applied response header (#380)
- e66aadc Update spec.md (#380)
- 6c52520 Bump golang.org/x/text from 0.3.6 to 0.3.8 in /conformance (#384)
- 83a61e7 Bump golang.org/x/net in /conformance (#385)
- ab44270 Updating go modules in conformance (#387)
- b962ef8 Update Jon Johnson's email (#392)
- 851ea52 Add OCI-Chunk-Min-Length header (#391)
- a1d7ad1 Specify Warning header usage (#393)
- fc2e963 whitespace lol (#393)
- ab32a6f spec and README: reduce to just image-manifest (#383)
- a330837 Add a patch status to recover failed requests (#366)
- 27ae6c2 conformance: make blob mount and upload checks more strict (#399)
- fa4a69a skip TLS verification during conformance tests (#394)
- c6400af Upgrade to reggie v0.6.1 to fix issue with Accept header (#400)
- 72a5455 Use artifactType from image manifest (#395)
- bea9b6f Automate conformance testing on PR using zot (#401)
- 8a73873 Merge branch 'main' of github.com:opencontainers/distribution-spec into automate-conformance (#401)
- f0122f6 move location check, allow missing bytes= prefix (#401)
- a5582e3 expect units in range header (#401)
- 18fdcbd fail CI if conformance fails (#401)
- 6520ed9 remove bytes= prefix on range header (#401)
- b077648 Allow missing bytes= prefix (#401)
- b0fa15c Merge branch 'opencontainers:main' into automate-conformance (#401)
- 1880a43 modify range check to not need bytes prefix (#401)
- 49af349 version: bump for v1.1.0-rc.2 release (#403)
- a3b708a version: roll HEAD back to -dev (#403)
- 529f2d1 Remove references to artifact manifest and artifact manfiest (#407)
- 8e2a64e Remove over-constrained references to manifests (#407)
- 09d29b1 Update README.md (#411)
- 7d2d9ff releases: use +dev as in-development suffix (#417)
- adeb3ac adds some description for adding dist extensions (#302)
- aef0f61 fix: delete manifest before blobs by default (#423)
- 73fe777 Conformance: fix inappropriate test HTTP method (#332)
- 135780a Fix incorrect test HTTP method (#331)
- a1eadff conformance: check response status before checking location (#420)
- d729b7a README.md: remove a dead link to chat.opencontainers.org (#422)
- c76f05b conformance: skip check (by default) for zero layers in image manifest  (#421)
- 99aba31 conformance: initial commit for refererrers test (#375)
- a738357 spec: more liberal separator for repository names (#425)
- efe2de0 spec: fix regexp (#426)
- caded17 conformance: do not fail on report generation failure (#419)
- 657d95d Test pull of manifest pushed by digest (#427)
- 215045b Fix delete of empty layer manifest (#428)
- e0e2768 Vendored image-spec should be private (#429)
- 46cff19 conformance: make references tests part of content discovery workflow (#430)
- 64d9453 Upgrade Go and dependencies including Ginkgo (#438)
- 118f77d MediaType is required in the descriptor (#439)
- 51c53ef Add a media type to the image manifest (#437)
- 42d2d6e version: bump for release of v1.1.0-rc.3
- 0326121 version: bump HEAD back to +dev
- 85b910a conformance: fix artifact layers content in setup (#447)
- f641ac6 Merge branch 'prep-1.1.0-rc.3-part-2' of github.com:jdolitsky/distribution-spec into HEAD
- 212108f Do not panic conformance when last request fails (#450)
- 9b5b19b conformance: OCI-Filters-Applied should return a literal (#449)
- b1e549b conformance: fix the subject's media-type (#451)
- e7db307 Add index with subject conformance test (#436)
- 2b3a8f4 Cleanup manifest push with a subject (#444)
- 60fc69c Rephrase the subject exclusion from validation (#445)
- b3f22a5 Specify content-type for referrers response (#452)
- 8617ec9 Rewrite conformance action to enable locking to spec version (#453)
- d53866a Merge branch 'main' of github.com:opencontainers/distribution-spec (#453)
- e452489 docs: small typo (#465)
- df1548b conformance: don't require http 202 for already-deleted manifest config (#478)
- 3940529 conformance: support OCI_REPORT_DIR (#473)
- efb0e36 spec: HEAD blob response should include content-length header (#482)
- b8d7db9 Parameters should not be included in Content-Type (#469)
- 900e87c Escape forward slash in regexp (#488)
- 91ba954 fix discovery teardown (#479)
- 1d6c168 Conformance: test for annotation pull up (#489)
- f3b894e Conformance: remove referrers digest header check (#492)
- d2cca2f README.md: Drop link to OCI scope table (#493)
- 9317d9b clarify where OCI-Chunk-Min-Length response headers are expected (#481)
- 961602b spec: clarify referrers response for index (#500)
- 3c7a4ac Blob delete permits the 405 response code (#499)
- 0a867d6 Support referrers to a missing manifest (#491)
- d7bc0ef version: bump for release of v1.1.0-rc.4 (#502)
- 57a38ee version: bump HEAD back to +dev (#502)
- ea280c5 Clarify the registry must accept a missing subject phrasing (#505)

## Diff

https://github.com/opencontainers/distribution-spec/compare/v1.0.1...main

## Votes

- [ ] @dmcgowan
- [x] @jzelinskie
- [x] @jonjohnsonjr
- [x] @jdolitsky
- [x] @mikebrow
- [x] @stevvooe
- [x] @sudo-bmitch
- [x] @vbatts

### CODE REVIEW

**Comment by sudo-bmitch** [comment]
For reference, here is the v1.1.0 milestone: https://github.com/opencontainers/distribution-spec/milestone/6?closed=1

**Comment by mikebrow** [comment]
related, dependent, vote... https://github.com/opencontainers/image-spec/pull/1161

**Comment by sudo-bmitch** [comment]
@dmcgowan @jzelinskie @jonjohnsonjr @mikebrow @stevvooe @vbatts PTAL

**Review by vbatts — APPROVED** [review]
:goat:

**Comment by jonjohnsonjr** [comment]
LGTM

**Review by jonjohnsonjr — APPROVED** [review]

**Review by jzelinskie — APPROVED** [review]

**Comment by mikebrow** [comment]
.

**Comment by sudo-bmitch** [comment]
> .

@mikebrow was that intended to be a review, or are you abstaining from the vote?

**Review by dmcgowan — APPROVED** [review]
Abstaining but we can move this along based on the current vote

**Review by stevvooe — APPROVED** [review]

**Review by mikebrow — APPROVED** [review]
LGTM
we can add more use cases in the followup..

**Pull request merged**
