### PR TITLE
MAINTAINERS: move vbatts to EMERITUS

### PR DESCRIPTION
**Pull request by vbatts**
Happy to still be brought into conversations, but do not want to slow progress of the active maintainers.

🐐🧁🧡

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]
🙇

**Review by jzelinskie — DISMISSED** [review]
Thank you for your service 🫡

**Review by dmcgowan — DISMISSED** [review]
👋🐐👑

**Review by sudo-bmitch — APPROVED** [review]
A huge thank you for everything you've done for so many years. It won't be the same without you.
🐐🧁♥️

**Review by jdolitsky — APPROVED** [review]

**Review by dmcgowan — APPROVED** [review]

**Comment by mikebrow** [comment]
Thx Vince.

**Pull request merged**
