### PR TITLE
1.0.0-rc1

### PR DESCRIPTION
**Pull request by vbatts**
this is for 9f55a32 to be tagged as 1.0.0-rc1
Email vote forthcoming

34 PRs merged since v1.0.0-rc0:

22583a5ea5a31a142611a8d5f4632f25e6ccca87 (#178) Add TODO under conformance
ea7a51757040c02a8d3a790aa2d474a238c815fd (#170) read env var only once
4b80706d310ecd40df3c1eae11e300401b367d3f (#149) Update Derek's email
ae19cbe28fafbe1d1e03d1c7bbdcd524c0347f69 (#144) Disable cookie handling by default
771e81c7514a22389b9671559d2d83898a6a21b7 (#143) Disable push teardown on Content Management workflow
1b49f74b6ad847eb06128473c55b25b67de59809 (#133) Provide option to disable empty-layer push test
fc1ba4807029e7f08e4c821cbcd2e617718dd2b2 (#138) Allow disabling 'pull' workflow
dca82e7f554f44f77750382bd1861b3e40131471 (#130) Enable user to hide skipped workflows in report
86948116194963a733f1cab62e2ecb4c3a196713 (#129) Modify manifest config to conform to image-spec
cd6b60dff9254b4037e5a3011e18bdfdea10c092 (#123) Improve HTML report and tidy code
7889f5564cddcde32aa706935decf6f6b416eaa4 (#127) changes.md: no longer needed
bbe424c0f6328023d8221678e6881e0586fd2dff (#105) Allow range of response codes for manifest delete
6a6ee23bbab1e5d07b45a10547265bc5249c3c4d (#107) Clarify tags listing behavior
263eb293b7d27ea1afde6796b8775d6109ed3f31 (#104) Move Dockerfile to conformance directory
a5f23be0671d4f1f4e75dbffa4d10f93b6aec5ba (#103) add space after <
1a06550f65633439c1e80a43cbec1fcf1781b721 (#98) Modify conformance Dockerfile filename
c38161c242f54894849d7a0d10a1ab7679044941 (#96) Fix misspelling of octet
7fca11e219163de019766edb1cb07b24ff18e551 (#95) Fix typo in pagination section
2560a81092d7a83c0db50231e69b584ac099d2f7 (#90) Conformance: Add CI, new tests, more report detail
174c8ced7e3c8fed6e8a5e1f9f8e821cfd4fb015 (#93) spec: quote in ticks
0383191317744f59cba3de142f23f8a400488da9 (#89) Add GitHub action definition for conformance tests
822d3a029084af27ea5ffdeaa2fc878ffaddee75 (#82) Introduce OCI Conformance Test Suite
0056e9844185a7ab8033bea304824f6c0864c9f7 (#80) spec: `Location` can be absolute or relative
828fb626bfe4fbd1c7d65331450803c6a7165fc0 (#78) spec: JSON formating
d8c049e0bb623e93608be10a6cd58707c6926e7c (#75) spec: clarify digest algorithm
35c06bdf7e266ca5a85f2c5f9dd23599a9ac3aed (#76) spec: session_id is clearer than UUID
b4e98332eccaf51d1974c9136caf67317bd99104 (#69) Remove _catalog API, reference as reserved
75485b8b99670c52a5d462995aefb532068508a2 (#67) Update blob patch status code to correct code
8e8fa5dd8bf94ea7e366a12c8fa797a161db5d79 (#61) Correct grammar for digest algorithm portion
d93cfa52800990932d24f86fd233070ad9adc5e0 (#50) *: Add OCI links to spec.
51b91fec22717b65442d45d64b23ca57afefb3ed (#57) updating link to code of conduct in org repository
6b5c54de2eda60cd8e2778c844879b8d5b4b3926 (#39) dist: check also for the path /tags
d10547bdcf1f4050b45e2f45b2e58aeb189807fb (#48) specs-go: Add ErrRegistry variable.
e58cbb4ab0b7bf20642d12b7a55dfa121a11ce93 (#35) *: copyright holder change

### CODE REVIEW

**Comment by jzelinskie** [comment]
LGTM
There might be minor flaws, but this will probably shake them out quicker than not putting something in people's hands.

**Comment by vbatts** [comment]
LGTM

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]
LGTM

**Comment by rchincha** [comment]
LGTM

**Comment by jdolitsky** [comment]
I may have made a mistake by "Squash and merging" this as we lost `9f55a32` ..

**Comment by vbatts** [comment]
ah yeah. There is no longer the commit to tag. 
I would never do the squash merge workflow on github projects anyway. It also causes the gpg signatures to get lost.
Let's see how to fix this...

**Comment by jdolitsky** [comment]
my apologies.. I think there is a way for us to disable that as the default merge option in GitHub settings for PRs with multi commits

**Comment by vbatts** [comment]
fixed now. Not sure what that revert-commit reference is about.

**Pull request merged**
