### PR TITLE
Add placeholder for content negotiation

### PR DESCRIPTION
**Pull request by jdolitsky**
Related to #212

### CODE REVIEW

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]
LGTM

**Comment by jonjohnsonjr** [comment]
@justincormack what do you think about this? I would also like to drop this entirely in favor of manifest list based mechanisms, but I'm reluctant to drop it entirely until registries stop downconverting to schema 1.

**Review by justincormack — APPROVED** [review]

**Comment by justincormack** [comment]
@jonjohnsonjr yeah thats fine. Note that the spec for Accept https://tools.ietf.org/html/rfc7231#section-5.3.2 says

  "If the header field is
   present in a request and none of the available representations for
   the response have a media type that is listed as acceptable, the
   origin server can either honor the header field by sending a 406 (Not
   Acceptable) response or disregard the header field by treating the
   response as if it is not subject to content negotiation."

So it is always fine to serve something the client did not ask for, and
totally ignore Accpet headers. I think we should recommend never sending a 406.

**Comment by jonjohnsonjr** [comment]
> origin server can either honor the header field by sending a 406 (Not
> Acceptable) response or disregard the header field by treating the
> response as if it is not subject to content negotiation.

Ooh this is nice. Will probably update GCR's behavior here to match. We might want to call out specifically some suggested behavior in the placeholder section around this? Right now we are returning a 404, which felt correct at the time, but is obviously non-conforming per the rfc. Just ignoring it would be wonderful, but I'm a bit concerned about breaking clients.

**Pull request merged**
